spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Vehicle-service
          uri: lb://Vehicle-service
          predicates:
            - Path=/api/v1/Vehicle-service/**

        #        - id: item-service
        #          uri: lb://item-service
        #          predicates:
        #            - Path=/api/v1/item/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**

        - id: local-auth-route
          uri: forward:/
          predicates:
            - Path=/api/v1/auth/**

#        ===================================
#    forward is very important poin this through forwoer the reqest to the Controller of Api-gatway
  # without  forward  the reqest will go to the User microservice
#    ========================================



server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
#==================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway