server:
  port: 8089

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # ඔයාගේ properties files තියෙන folder එකේ path එක මෙතනට දෙන්න
          search-locations: file:../config-repo
#          classpath:/config-repo




server:
  port: 8089

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ManuthLakdiw/AGMS-microservice
          search-paths: config-repo
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

