server:
  port: 8089

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/savindunawanjana2003/Microservices-architecture-practis.git
          search-paths: config-repo
          clone-on-start: true
          #due to Private Repo , must need   authenticetions
          username: savindunawanjana2003
          password: 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
          # recomend ( you can use env)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true